# GitHub Pages Configuration
title: Tiation - Transforming Systems for Human Flourishing
description: A unified platform for systemic change and human flourishing
url: https://tiation.github.io
baseurl: /tiation

# Build settings
plugins:
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - package.json
  - pnpm-workspace.yaml
  - turbo.json
  - setup-github-pages.sh
  - node_modules
  - .git
  - .gitignore
  - api/
  - apps/
  - infrastructure/
  - packages/
  - scripts/
